jobs:
- job: Job
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'my-acr-connection'   # 🔄 UPDATE this
      repository: 'webappimage'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        latest

  - task: AzureWebAppContainer@1
    inputs:
      azureSubscription: 'my-azure-subscription'  # 🔄 UPDATE this
      appName: 'your-webapp-name'                # Replace with actual App Service name
      containers: 'priyacrdemo.azurecr.io/webappimage:latest'
